import { type NextPage } from "next";
import Head from "next/head";
import { type ChangeEvent, useState } from "react";
import debounce from "lodash/debounce";

const getExercises = async (searchTerm: string) => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/todos?_limit=10`
  );

  const data = (await res.json()) as { title: string }[];
  return data;
};

const SearchBar = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [isSearchInputFocused, setIsSearchInputFocused] = useState(false);

  const [searchResults, setSearchResults] = useState<string[]>([]);

  const handleSearch = (e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.value.length > 0) {
      setIsSearchInputFocused(true);
      getExercises(e.target.value)
        .then((data) => {
          console.log("data", data);
        })
        .catch((err) => {
          console.log(err);
        });

      setSearchResults(["hi", "hello"]);
    } else {
      setIsSearchInputFocused(false);
      setSearchResults([]);
    }
    setSearchTerm(e.target.value);
  };
  return (
    <div className="border-b px-8 py-4">
      <input
        type="text"
        placeholder="Search"
        className="w-full p-2 text-2xl"
        onChange={debounce(
          (e) => handleSearch(e as ChangeEvent<HTMLInputElement>),
          1000
        )}
        onBlur={() => setIsSearchInputFocused(false)}
      />

      <div
        className={
          "flex max-h-[200px] min-h-[200px] flex-col space-y-2 overflow-y-scroll bg-slate-400" +
          (isSearchInputFocused ? "" : " hidden")
        }
      >
        {searchResults.map((result, index) => (
          <div key={index} className="">
            {result}
          </div>
        ))}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Gym Planner</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <SearchBar />
        <p>hi</p>
      </main>
    </>
  );
};

export default Home;
