export const exercises = [
  {
    name: "Goblet Squat",
    id: "Goblet_squat_M_WorkoutLabs",
    muscleGroups: ["legs"],
    equipment: ["dumbbell"],
  },
  {
    name: "Stiff Leg Barbell Deadlift",
    id: "Stiff_Leg_Barbell_Deadlift_M_WorkoutLabs",
    muscleGroups: ["legs"],
    equipment: ["barbell"],
  },
  {
    name: "Dumbbell Walking Lunges",
    id: "Dumbbell_Walking_Lunges",
    muscleGroups: ["legs"],
    equipment: ["dumbbell"],
  },
  {
    name: "Bodyweight Sumo Squats",
    id: "Bodyweight_Sumo_Squats-1",
    muscleGroups: ["legs"],
    equipment: ["bodyweight"],
  },
  {
    name: "Bodyweight Calf Raises",
    id: "Bodyweight_Calf_Raises_M_WorkoutLabs",
    muscleGroups: ["legs"],
    equipment: ["bodyweight"],
  },
  {
    name: "Dumbbell Squat",
    id: "Dumbbell_Squat_M_WorkoutLabs",
    muscleGroups: ["legs"],
    equipment: ["dumbbell"],
  },
  {
    name: "Barbell Deadlift",
    id: "Barbell_Deadlift_M_WorkoutLabs",
    muscleGroups: ["legs"],
    equipment: ["barbell"],
  },
  {
    name: "Bulgarian Split Squat",
    id: "Bulgarian_Split_Squat_M_WorkoutLabs",
    muscleGroups: ["legs"],
    equipment: ["dumbbell"],
  },
  {
    name: "Barbell Hip Thrusts",
    id: "Barbell_Hip_Thrusts-1",
    muscleGroups: ["legs", "glutes"],
    equipment: ["barbell"],
  },
  {
    name: "Hip Circles",
    id: "Hip_Circles",
    muscleGroups: ["hips"],
    equipment: ["bodyweight"],
  },
  {
    name: "One Arm Dumbbell Row",
    id: "One_Arm_Dumbbell_Row_M_WorkoutLabs",
    muscleGroups: ["back"],
    equipment: ["dumbbell"],
  },
  {
    name: "Seated Arnold Dumbbell Press",
    id: "Seated_Arnold_Dumbbell_Press_M_WorkoutLabs",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbell"],
  },
  {
    name: "Incline Dumbbell Press",
    id: "Incline_Dumbbell_Press_M_WorkoutLabs",
    muscleGroups: ["chest"],
    equipment: ["dumbbell"],
  },
  {
    name: "Dumbbell Incline Row",
    id: "Dumbbell_Incline_Row_M_WorkoutLabs",
    muscleGroups: ["back"],
    equipment: ["dumbbell"],
  },
  {
    name: "Hammer Curls",
    id: "Hammer_Curls_M_WorkoutLabs",
    muscleGroups: ["biceps"],
    equipment: ["dumbbell"],
  },
  {
    name: "Concentration Curls",
    id: "Concentration_Curls_M_WorkoutLabs",
    muscleGroups: ["biceps"],
    equipment: ["dumbbell"],
  },
  {
    name: "Standing Dumbbell Curl",
    id: "Standing_Dumbbell_Curl_M_WorkoutLabs",
    muscleGroups: ["biceps"],
    equipment: ["dumbbell"],
  },
  {
    name: "Seated Tricep Press",
    id: "Seated_Tricep_Press_M_WorkoutLabs",
    muscleGroups: ["triceps"],
    equipment: ["dumbbell"],
  },
  {
    name: "Dumbbell Shrug",
    id: "Dumbbell_Shrug_M_WorkoutLabs",
    muscleGroups: ["shoulders", "traps"],
    equipment: ["dumbbell"],
  },
  {
    name: "Dumbbell Bench Press",
    id: "Dumbbell_Bench_Press_M_WorkoutLabs",
    muscleGroups: ["chest"],
    equipment: ["dumbbell"],
  },
  {
    name: "Dumbbell Floor Press",
    id: "Dumbbell_Floor_Press",
    muscleGroups: ["chest", "triceps"],
    equipment: ["dumbbell"],
  },
  {
    name: "Standing Overhead Dumbbell Press",
    id: "Standing_Overhead_Dumbbell_Press_M_WorkoutLabs",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbell"],
  },
  {
    name: "Dumbbell Lateral Raise Power-Partials",
    id: "Dumbbell_Lateral_Raise_Power-Partials_M_WorkoutLabs",
    muscleGroups: ["shoulders"],
    equipment: ["dumbbell"],
  },
  {
    name: "Tricep Dumbbell Kickback",
    id: "Tricep_Dumbbell_Kickback_M_WorkoutLabs",
    muscleGroups: ["triceps"],
    equipment: ["dumbbell"],
  },
  {
    name: "Plank",
    id: "Plank_M_WorkoutLabs",
    muscleGroups: ["core"],
    equipment: ["bodyweight"],
  },
  {
    name: "Resistance Crunches",
    id: "Resistance_Crunches_M_WorkoutLabs",
    muscleGroups: ["core"],
    equipment: ["bodyweight"],
  },
  {
    name: "Side Plank",
    id: "Side_plank_M_WorkoutLabs",
    muscleGroups: ["core"],
    equipment: ["bodyweight"],
  },
];
